### ISSUE TITLE
Create local, context-sensitive help text for all dialogs

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#169]
_(assign to EVGrokker)_

Create local help text for all dialogs:
- [x] Waypoint Inspector (issue #167)
- [x] Edit Waypoint (issue #168)
- [x] Add Waypoint (issue #170)
- [x] New Trip (issue #172)
- [x] Supercharger Inspector (issue #175)
- [x] Charger inspector (issue #176)
- [x] Settings (issue #173 )
- [x] My Cars (issue #179)
- [x] Maintain Favorites (issue #180)
- [x] Edit Segment Details (issue #181)
- [x] Filter Chargers (issue #182)
- [x] Rate Trip (issue #183)
- [x] Archived Trips
- [x] Add Segment
- [x] Feedback Report (issue #210)

**Comment by EVGrokker** [comment]
Note that for all of these help dialogs, the issue is already formatted in HTML using the format you've already established.

**Comment by aesculus** [comment]
> Note that for all of these help dialogs, the issue is already formatted in HTML using the format you've already established.

Unfortunately when they get into Git the HTML get applied and the tags are lost. NBD. I'll just copy and paste the text, but it's helpful to see the context.

**Comment by EVGrokker** [comment]
Edit the comment and you'll be able the see the HTML. If you can't edit it, I'll copy/paste in such a way that exposes the HTML.

**Comment by aesculus** [comment]
Ah. What a hack. :-)

Thank you. This will be a lot easier for me.

**Comment by aesculus** [comment]
Now I have a bit of a dilemma to work out. The UI framework I use only allows one panel at a time to be shown (exclusive of the popups in the map). So if I have the New Trip or Add Waypoint dialog up, I cannot display the help panel.  I have to close the dialog first.  You may have noticed this issue with the Favorites selection panel, why the New Trip or Add Waypoint goes away if you select the black heart.

So now we have to think about the help in these situations. Do we:
- Close the dialog down until the help is done and then reload it?
- Come up with another scheme to show the help?
- Don't have context help?

**Comment by EVGrokker** [comment]
I think the value of context-sensitive help outweighs the UI elegance. I'd vote for option 1, dismiss the dialog invoking help until help is dismissed, then redisplay the dialog. 

It may be that after using the implementation, we'd rethink this, but I'm sure it would be acceptable for 1.1.3.

**Comment by aesculus** [comment]
OK. I am trying to come up with a hack but so far no good.  And of course I need to find a way to preserve state between showings.

Nothing is ever easy. :-)

**Comment by EVGrokker** [comment]
Could you expand the dialog panel downward to expose the help, then collapse it back up when user dismisses it?

**Comment by EVGrokker** [comment]
Is this only an issue with the waypoint inspector style of pop-up? What about the Add Waypoint dialog, which is a different appearance?

**Comment by EVGrokker** [comment]
What if help dismisses the invoking dialog, displays the contextual help, and then simply returns to the plan screen?

**Comment by aesculus** [comment]
That is easy.

**Comment by EVGrokker** [comment]
In the interest of expediency and prioritizing your time on more important features, that seems an acceptable compromise.

**Comment by aesculus** [comment]
I might have found a hack, but it still needs some work. It will also require a Close button on the help panel, which probably should be on all the other help panels too for UI consistency even though you don't need them when they open outside of modal dialogs.

**Comment by aesculus** [comment]
Got it. If the button (X) is OK right next to the Help word, we are good. Picture in a few minutes.

**Comment by aesculus** [comment]
OK. Here is a sample

![image](https://cloud.githubusercontent.com/assets/283364/24824850/5cab5378-1bc8-11e7-81ee-b12c2d64100e.png)

**Comment by EVGrokker** [comment]
I think the help button would be better on the left, and using the circled '?' icon instead of text. 
👍

**Comment by aesculus** [comment]
![image](https://cloud.githubusercontent.com/assets/283364/24824949/249248f0-1bca-11e7-978f-24185364dbff.png)

**Comment by EVGrokker** [comment]
Good. Last fussy design suggestion for this layout - what would you think about keeping the help icon aligned against the left border of the dialog, as it is now, and pushing the Cancel and Save buttons over to align against the right border? This would apply to all dialogs of this style.

**Comment by aesculus** [comment]
Sure. But for some reason I would do the opposite. That way it matches the other dialogs where the help icon is on the right too.

So move the help icon to the far right and have the two big buttons on the left because you will scan those first from left to right.

**Comment by EVGrokker** [comment]
My instinct is always to look to the lower right of a dialog for the 'do it' button.

I agree that consistency with the other dialogs is important, so after having seen both layouts I'd suggest moving the help icon to the left side on the waypoint inspector and other dialogs of that style.

**Comment by aesculus** [comment]
OK.

**Comment by aesculus** [comment]
Got the help working now. Probably violates some UI standard in that I have panels overlaying modal dialogs. It might break too if the UI framework ever changes but that is another story.

One quick question: I used the have the word Help appear at the top of every help panel. Your help text does not include that.  Did you think it redundant and a waste of space?  Anyway I did not include the Help word in these panels, partially because Help was H3 and yours start with the help name (ex Settings) at H3.

**Comment by EVGrokker** [comment]
I have no opinion on the <h> tag you use, that's all up to you. I was attempting to mimic the style I thought you were using.

With respect to including 'Help' at the head of the help text, I do think it's redundant. They touched the help icon to launch the help panel. Their expectation is that they're going to see help associated with the modal dialog they were viewing, so I don't think appending 'Help' on the topmost <h> title is necessary or expected.

With respect to violating UI standards, if you need to re-architect the design at some point, I'd be OK with the underlying modal dialog dismissing when help is summoned if necessary. As you say, that can wait for another day.

**Comment by aesculus** [comment]
Added Archived Trips

**Comment by aesculus** [comment]
Also need a Add Segment help. At first I thought we could just use the New Trip one but it has significant differences and needs an explanation on why you would add a segment.

**Comment by aesculus** [comment]
Also need help for the Feedback Report dialog

**Comment by aesculus** [comment]
Complete in V1.1.4
