### ISSUE TITLE
Tips & Tricks Index

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#241]
**Basic Tutorials**: Checked items are ready for review. Top of the list is next to be published.
- [x] Route Planning: Find Us with Destination Charging (#322)
- [x] From the Frunk: All About Trips, Routes and Segments (#258) (waiting on 1.2)
- [ ] Route Planning: Plug-In NCW (#364) (waiting on 1.2)
- [ ] Using EVTO in the car (Preflight) during your trip as a companion to the in-car nav system (calendar export of waypoints, segments) (#292) (waiting on 1.2)
- [ ] Using Favorites to speed up trip planning (Home, Work, frequently-visited charger) (Wait until revisions to the Favorites UI completed: issues #8, #27, #28, #77) (waiting on 1.3)
- [ ] EVTO vs Browser-based trip planning tools
- [ ] From the Frunk: The Origin Story (#347)

**Advanced Tutorials**: Checked items are ready for review. Top of the list is next to be published.
- [x] Route Planning: The Journey is the Destination (#324)
- [x] Route Planning: Multi-day, Multi-segment Trips (#267)
- [x] Resource Planning: Reserving Energy for Local Excursions (#294) (1.3)
- [ ] Resource Planning: Winnemucca - Boise https://teslamotorsclub.com/tmc/threads/winnemucca-nv-to-boise.44688/
- [ ] Resource Planning: Reserving Energy for the Return Trip (go-kart story)
- [x] Using Plugshare, RV Parky, [My Scenic Drives](https://www.myscenicdrives.com/) and other resources for destination charging
- [x] Fine-tuning EVTO's prediction accuracy using Power Factor (#295) (Wait for resolution of #220)

**Terminology (#254)**
- [x] Reachability: Red at or below 5%. Yellow: 5 to Reserve SoC. Green: > Reserve SoC.

**Posted tutorials (closed)**
- [x] From the Frunk: A User's Guide to EVTO Terminology (#254) 2017-04-28
- [x] Route Planning: Shifting from Auto to Manual (#277) 2017-04-28
- [x] Route Planning: The Sounds of Silence (#340) 2017-05-05
- [x] Route Planning: A One-day Scenic Drive (#243) 2017-05-10

Link to [DAG Basic Tutorials](http://www.digitalautoguides.com/evto-tutorials/#evto_basic)
Link to [DAG Advanced Tutorials](http://www.digitalautoguides.com/evto-tutorials/#evto_advanced)

**Comment by aesculus** [comment]
Shell here:

http://www.digitalautoguides.com/evto-tutorials/

**Comment by aesculus** [comment]
Out of date.
