### ISSUE TITLE
Upcoming Release Objectives: 2.0

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#290]
### Major New Features ###
- Single-trip optimization
- Updated charger pin shapes
- Split battery appearance update

### Annoyances ###
- [x] #197 - When Location Services enabled after initially disallowing, setting is not sticky in EVTO, and system-level Location Services for EVTO are not enabled.
---
### Critical bugs ###
- [x] (none at this time)
---
#### Internal tweaks ####
- [x] Single-trip optimization (#10)
- [x] Implement status dialog communicating optimization/calculation/etc status (#363)
- [x] Creating new segments without charger should inherit SoC, not assume full charge (#274)
- [x] Revise initial screen sequence for freshly installed app (#45)
- [x] Changing Trip Date May not Refresh Weather (#95)
- [x] Delete Last Segment (#299)
- [x] Minimum Departure SoC for supercharger stops (#213)
- [x] Updated split battery feature (issues #126, #232, #233)

---
#### New Features ####
- [x] Implement Share feature (export to calendar) in Waypoint Inspector with revised title formatting. (#118)
- [x] **Main menu**: Add **Edit Trip Details** item  (#94, #97, #315 )
- [x] **New Trip** dialog: Add departure date/time (#296)
- [x] **Settings**: Add default trip departure time (#297)
- [x] **Plan Trip** screen: Add option to display current location (#117)
---
#### UI Tweaks ####
- [x] Redesign charger pins (#343)
- [x] Rename **Trip Segments** to **Trip Inspector**, **Segment Summary** to **Segment Inspector** (#284). 
- [x] Review header font size (#221, #222, #223)
- [x] **Edit Segment Details**: Add warning dialog when user sets departure date earlier than today 
- [x] **Edit Segment Details**: Change cabin temperature field to a picker control (#184, #280)
- [x] **My Cars**:  Add the Model X 5 Seater as an option in (#302)
- [x] **My Cars**: Improve UI (scrollability, discoverability) (#187, #316)
- [x] **Main menu**:  Update Tutorials link (#317)
---
### Documentation: Ready to Integrate ###
- [x] Plan Help: Update Map Buttons section, adding crosshairs button, new current location feature, describing long touch on map, renaming Segment Summary to Trip Inspector (#304) (waiting on #284)
- [x] Waypoint Inspector Help: Add description of delete function when deleting hinge point, special case for last destination/segment. (#305) 
---
### Documentation: Waiting on Feature Implementation ###
- [ ] Add section to Main screen Help describing **Edit Trip Details** dialog. (waiting on #94, #97)
- [x] Create Edit Trip Details local help content (waiting on #94, #97)
- [ ] Review Waypoint Inspector Help for **Share** feature  (waiting on #118)
- [ ] Review New Trip dialog help (waiting on #296)
- [ ] Review My Cars dialog help (waiting on #302)
- [ ] Review Settings dialog help (waiting on #297)
- [ ] Review Edit Segment Details dialog help (waiting on #184)
---
### Tutorials ###
- [ ] Fine-tuning EVTO's prediction accuracy using Power Factor, Towing (#295) (waiting on #303, #306)
---
### DAG Website ###
_(**Publish** = post content to its own page, create an enabled link. 
**Add** = post content to its own page, create a hidden link)_

---

### Major New Features ###
- Calendar export improvements
- Segment Summary update

### New Features / Enhancements ###
- [x] **Segment Summary** redesign, navigation between segments (issue #227).
- [x] Add segment metrics to Trip Segments (issue #279)
- [x] Rangefinder feature (issue #291)
- [x] Improve calendar export content (issue #37)
- [x] Revising **Segment Details** portrait mode layout on phone-sized devices (issue #240)

### Tutorials ###
- [ ]  Resource Planning - Reserving Energy for Local Excursions (#294)

---
### Major New Features ###
- Favorites management updates
- Trip Details redesign

### New Features / Enhancements ###
- [ ] Favorite/Dislike management (issue #8, #28, #77)
- [x] Add ability to access address book when specifying waypoint/origin/destination address (issue #44)
- [x] Add mechanism to favorite a waypoint when creating it (issue #142, #162 )
- [x] Hide inactive segment pins when overlapping active segment pins (issue #275)
- [x] Keep Waypoint Inspector open after converting auto charger to required stop (issue #268)
- [ ] Add Google POIs to route (issue #229)
- [x] Review Power Factor UI (issue #220)
- [x] Add default values for Payload, Cabin Temp in My Cars dialog (issue #135)
- [x] Review charger waypoint behavior, SoC labelling (#213, #103)
- [x] Touching title bar in Plan screen opens Edit Segment Details dialog (Issue #134)
- [x] Redesign Trip Details panel (issue #41)
- [x] Long press on Globe button pops up Trip options (issue #293)

### Tutorials ###
- [ ] Using EVTO with Tesla's Navigation System (#292)

---
### New Features / Enhancements ###
- [ ] Drag and Drop waypoint reordering in Segment Inspector (issue #36)
- [ ] Ability to add car-specific, user-supplied background images for Main screen (issue #2)
- [x] Add Open in Google Maps (issues #39, #40)
- [ ] Add other route optimization options (minimize travel time, energy, etc) (issue #74)
- [ ] Redesign Current Trips, Archived Trips panels (issue #22)
- [ ] Edit Segment Details: Add option specifying _depart at_ or _arrive by_ time (issue #4)
- [ ] Vampire drain factor on extended non-charging layovers (issue #1)
- [ ] Add a feature to avoid leaving the country #298
